spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    username: root
    password: P@ssw0rd123
    url: jdbc:mysql://localhost:3306/ashokit_ecomm

    jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
